################################################################################
##
## Filename:	./rtl.make.inc
##
## Project:	ICO Zip, iCE40 ZipCPU demonstration project
##
## DO NOT EDIT THIS FILE!
## Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
## DO NOT EDIT THIS FILE!
##
## CmdLine:	../../../autofpga/trunk/sw/autofpga ../../../autofpga/trunk/sw/autofpga -o . global.txt bkram.txt buserr.txt clock.txt dlyarbiter.txt pic.txt pwrcount.txt version.txt busconsole.txt gpio.txt zipbones.txt
##
## Creator:	Dan Gisselquist, Ph.D.
##		Gisselquist Technology, LLC
##
################################################################################
##
## Copyright (C) 2017, Gisselquist Technology, LLC
##
## This program is free software (firmware): you can redistribute it and/or
## modify it under the terms of  the GNU General Public License as published
## by the Free Software Foundation, either version 3 of the License, or (at
## your option) any later version.
##
## This program is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
## FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
## target there if the PDF file isn't present.)  If not, see
## <http://www.gnu.org/licenses/> for a copy.
##
## License:	GPL, v3, as defined and found on www.gnu.org,
##		http://www.gnu.org/licenses/gpl.html
##
##
################################################################################
##
##
BKRAM:= memdev.v

PICD := cpu

PIC  := $(addprefix $(PICD)/,icontrol.v)
ZIPCPUD := cpu

ZIPCPU  := $(addprefix $(ZIPCPUD)/,cpuops.v dblfetch.v div.v icontrol.v idecode.v memops.v wbdblpriarb.v zipcpu.v zipbones.v)
BUSDLYD := cpu

BUSDLY  := $(addprefix $(BUSDLYD)/,busdelay.v wbpriarbiter.v)
PPORTD := ../pport

PPORT  := $(addprefix $(PPORTD)/,ppio.v pport.v ufifo.v)
WBUBUSD := wbubus

WBUBUS  := $(addprefix $(WBUBUSD)/,wbuconsole.v wbufifo.v wbucompactlines.v wbucompress.v wbudecompress.v wbudeword.v wbuexec.v wbuidleint.v wbuinput.v wbuoutput.v wbureadcw.v wbusixchar.v wbutohex.v wbconsole.v)
GPIO:= wbgpio.v

VFLIST := main.v  $(BKRAM) $(PIC) $(ZIPCPU) $(BUSDLY) $(PPORT) $(WBUBUS) $(GPIO)
AUTOVDIRS :=  -y $(PICD)  -y $(ZIPCPUD)  -y $(BUSDLYD)  -y $(PPORTD)  -y $(WBUBUSD) 
